spring:
  server:
    port: 8080
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update       # Автоматическое обновление схемы базы данных
    show-sql: true           # Показ SQL-запросов в логах
    properties:
      hibernate:
        format_sql: true      # Форматирование SQL-запросов
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false